name: Deploy Production

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Validate and Test
  validate:
    name: Validate Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run linter
        run: npm run lint
        
      - name: Type check
        run: npm run check-types

  # Deploy Supabase Backend
  deploy-backend:
    name: Deploy Backend (Supabase)
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest
          
      - name: Deploy to Supabase
        run: |
          echo "Backend deployment will be configured after Supabase setup"
        # Uncomment after Supabase is set up:
        # cd apps/backend
        # supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
        # supabase db push
        # env:
        #   SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

  # Deploy Web to Vercel
  deploy-web:
    name: Deploy Web (Vercel)
    needs: [validate, deploy-backend]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy to Vercel
        run: |
          echo "Web deployment will be configured after Vercel setup"
        # Uncomment after Vercel is set up:
        # uses: amondnet/vercel-action@v25
        # with:
        #   vercel-token: ${{ secrets.VERCEL_TOKEN }}
        #   vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        #   vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        #   working-directory: ./apps/web